### ISSUE TITLE
UnboundLocalError: local variable 'currentAlbum' referenced before assignment

### ISSUE THREAD

**Issue by gracca** [geekpradd/PyLyrics#2]
```python
In [18]: tracks = myalbum.tracks()
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-18-a5a5cf859bd5> in <module>()
----> 1 tracks = myalbum.tracks()

/home/german/.local/lib/python2.7/site-packages/PyLyrics/functions.pyc in tracks(self)
     36                 return self.singer
     37         def tracks(self):
---> 38                 return PyLyrics.getTracks(self)
     39 
     40 class PyLyrics:

/home/german/.local/lib/python2.7/site-packages/PyLyrics/functions.pyc in getTracks(album)
     67                                 currentAlbum = al
     68                                 break
---> 69                 songs =[Track(song.text,album,album.artist()) for song in currentAlbum.findNext('songs').findAll('item')]
     70                 return songs
     71 

UnboundLocalError: local variable 'currentAlbum' referenced before assignment

```

**Comment by geekpradd** [comment]
Sorry for the inconvenience.. Will try to fix it

**Comment by groadabike** [comment]
Dear geekpradd
I found that the issue is that the API change
I had the same error and I fix it changing line 62
url = "http://lyrics.wikia.com/api.php?artist={0}&fmt=xml".format(album.artist())
by 
url = "http://lyrics.wikia.com/api.php?action=lyrics&artist={0}&fmt=xml".format(album.artist())

Also, I found that in some lyrics from QUEEN I receive an <img> and <span> tag
so I added both in line 92 
from
for tag in ['div','i','b','a']:
to 
for tag in ['div','i','b','a', 'span', 'img']:

Best regards

**Comment by groadabike** [comment]
Sorry
Also it is necessary to add 

import sys
reload(sys)
sys.setdefaultencoding('utf8')

at the beggining of the file.
fix some error that I receive also with Queen

**Comment by geekpradd** [comment]
@groadabike, I'm not developing this plugin anymore but I can merge your pull request if you can open one with the fixes.
